package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import objects.User;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class LoginPageController implements Initializable {
	@FXML
	private PasswordField pb;
	@FXML
	private TextField username;
	@FXML
	private Button loginButton;
	@FXML
	private Label label;
	@FXML
	private Button SignUpButton;
	@FXML
	private TextField NewName;
	@FXML
	private PasswordField NewUserPassword;
	@FXML
	private TextField NewUserName;
	@FXML
	private Label RegistrationErrorLabel;
	
	private static HashMap<String,String> AccountList = new HashMap<String,String>();

	public HashMap<String,String> getAccountList() {
		return AccountList;
	}

	public void setAccountList(HashMap<String, String> accountList) {
		AccountList = accountList;
	}
	
	
	
	

	// Event Listener on Button[#loginButton].onAction
	@FXML
	public void login(ActionEvent event) throws IOException {
		loadAccountInfo();
		// TODO Autogenerated
		System.out.println("log in button click");
		if (checkLogin(this.username.getText(), this.pb.getText())) {
			label.setText("Your password has been confirmed");
			label.setTextFill(Color.rgb(21, 117, 84));
			pb.clear();
			Parent homescreen = FXMLLoader.load(getClass().getResource("AfterLogInPage.fxml"));
			Scene loginScene = new Scene(homescreen);
			Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
			window.setScene(loginScene);
			window.show();
		} else {
			label.setText("Your password has been confirmed");
			label.setTextFill(Color.rgb(21, 117, 84));
			pb.clear();
			Parent homescreen = FXMLLoader.load(getClass().getResource("LogInPage.fxml"));
			Scene loginScene = new Scene(homescreen);
			Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
			window.setScene(loginScene);
			window.show();

		}
	}

	private boolean checkLogin(String username, String password) {
		if(AccountList.containsKey(username)) {
			if(AccountList.get(username).equals(password)) {
				return true;
			}else {
				label.setText("Your password is incorrect!");
				label.setTextFill(Color.rgb(210, 39, 30));
				return false;
			}
		}else {
			label.setText("Username not found!");
			label.setTextFill(Color.rgb(210, 39, 30));
			label.setVisible(true);
		
		// TODO Auto-generated method stub
		return false;
	}
	}
	
	private void loadAccountInfo() throws IOException {
		File recordFile = new File("/Users/jackdansbury/eclipse-workspace/ds1Project/AppUsers.txt");
		FileReader fileReader = new FileReader(recordFile);
		BufferedReader bufferedReader = new BufferedReader(fileReader);
		String line;
		while ((line = bufferedReader.readLine()) != null) {
			String[] temp = new String[2];
					temp = line.split(",");
					User user = new User(temp[0],temp[1]);
					AccountList.put(user.getUsername(),user.getPassword());
		}
		fileReader.close();
		
	}
	

	// Event Listener on Button[#SignUpButton].onAction
	@FXML
	public void register(ActionEvent event) {
		// TODO Autogenerated
		if(!checkLogin(NewUserName.getText(),NewUserPassword.getText()))
			
		   try (BufferedWriter bw = new BufferedWriter(new FileWriter("AppUsers.txt", true))) {
			   bw.write(NewUserName.getText()+",");
			   bw.write(NewUserPassword.getText());
			   bw.newLine();
			   label.setText("Account Created");
	        label.setTextFill(Color.rgb(21, 117, 84));
	        Parent homescreen = FXMLLoader.load(getClass().getResource("AfterLogInPage.fxml"));
			Scene loginScene = new Scene(homescreen);
			Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
			window.setScene(loginScene);
			window.show();
		   }catch(Exception e) {
			   e.getMessage();
	}
		  
}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
	
	}


}